FROM maven:3.9.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2: ejecutar el JAR
FROM amazoncorretto:17-alpine-jdk
WORKDIR /app
COPY --from=build /app/target/TrabajoAW-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]